name: Build and Push Docker Image to Docker Hub
run-name: Build Docker Image ${{ inputs.image_tag }}
on:
  # push:
  #   paths:
  #     - '!README.md'
  #     - '!public/**'
  #     - '!uploads/**'
  #     - '!test/**'
  #     - '**.js'
  #     - '**.ts'
  #     - '**.yaml'
  #   branches:
  #     - 'domain/nika'
  #     - '!master'
  #     - '!develop'
  #     - '!feature/**'
  #     - '!bugfix/**'
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Hub image tag"
        required: true

jobs:
  push_to_registry:
    runs-on: [self-hosted, build, huongspa]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_REPOSITORY }}
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:${{ inputs.image_tag }} .
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}:${{ inputs.image_tag }}
      # Implement secret - Not show in console
      # - run: echo ${{secrets.ACCESS_TOKEN}}
      # Hidden vars
      # - run: |
      #   API_TOKEN=$(node cli.js dqwdqwd)
      #   echo "API_TOKEN=$API_TOKEN" >> $GITHUB_ENV
      #   echo "::add-mask::$API_TOKEN"
      #   echo token $API_TOKEN
